name: Release

on:
  push:
    tags:
      - "v*"

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
            assetNamePattern: 'Ntfy-macOS-Apple-Silicon[ext]'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
            assetNamePattern: 'Ntfy-macOS-Intel[ext]'
          - platform: 'ubuntu-24.04'
            args: ''
            assetNamePattern: 'Ntfy-Linux-x64[ext]'
          - platform: 'windows-latest'
            args: ''
            assetNamePattern: 'Ntfy-Windows-x64-Setup[ext]'
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

      - name: Setup Node
        uses: actions/setup-node@v4
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        with:
          node-version: lts/*
          cache: "pnpm"

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Ubuntu Dependencies
        if: matrix.platform == 'ubuntu-24.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev libpipewire-0.3-dev libgbm-dev patchelf

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: src-tauri

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Next.js
        run: pnpm run build:ui

      - name: Read Version
        id: version
        shell: bash
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=v$VERSION" >> $GITHUB_OUTPUT

      - name: Build Tauri
        uses: tauri-apps/tauri-action@v0.6.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: ${{ steps.version.outputs.version }}
          releaseName: "Ntfy App ${{ steps.version.outputs.version }}"
          releaseBody: "See the [changelog](https://github.com/rubix-studios-pty-ltd/ntfy-app/blob/main/CHANGELOG.md) for details."
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
          assetNamePattern: ${{ matrix.assetNamePattern }}
